version: '3.9'

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=name
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=name
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
